// !HACK babel does not support const enums, hence this here uses "let"
export enum WP_ERROR_CODES {
  NO_MATCH_SINGULAR = 'NO_MATCH_SINGULAR',
  MULTIPLE_MATCHES_SINGULAR = 'MULTIPLE_MATCHES_SINGULAR',
  MENU_FETCH_FAIL = 'MENU_FETCH_FAIL',
  SINGULAR_FETCH_FAIL = 'SINGULAR_FETCH_FAIL',
  CATEGORY_POSTS_FETCH_FAIL = 'CATEGORY_POSTS_FETCH_FAIL',
}
