version: '3.7'

services:
  wp:
    image: wordpress
    container_name: basakbeykoz_wp_d
    # user: "${UID}:${GID}"
    restart: on-failure
    # privileged: true
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_NAME: exampledb
      WORDPRESS_DB_PASSWORD: examplepass
    depends_on:
      - db
    volumes:
      # These shall be copied by the dockerfile
      - ./etc/apache/apache.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./etc/uploads/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./scripts/basakbeykoz_wp_d/:/scripts
      - ./plugins:/var/www/html/wp-content/plugins
      # The theme requires building and then copying by the dockerfile
      - ./themes:/var/www/html/wp-content/themes
      # These shall come from persistent storage in production
      - ./backups/uploads:/var/www/html/wp-content/uploads

  db:
    image: mysql:5.7
    container_name: basakbeykoz_db_d
    restart: on-failure
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db:/var/lib/mysql
      - ./backups/sql:/backups/sql
      - ./scripts/basakbeykoz_db_d:/scripts

volumes:
  db:
