enum ACTION_TYPES {
  FETCH_MENU,
  FETCH_POSTS,
  FETCH_POST,
  FETCH_CATEGORY,
  FETCH_CATEGORIES,
  FETCH_CATEGORY_POSTS,
  FETCH_PAGE,
  FETCH_SINGULAR,
  IS_FETCHING,
  IS_DISPLAYING,
  NAV_TO_CONTENT,
  IS_MENU_OPEN,
  SET_REF,
}

export default ACTION_TYPES;
