export enum ACTION_TYPES {
  FETCH_MENU,
  FETCH_POSTS,
  FETCH_POST,
  FETCH_CATEGORY,
  FETCH_CATEGORIES,
  FETCH_CATEGORY_POSTS,
  FETCH_PAGE,
  FETCH_SINGULAR,
  IS_FETCHING,
  IS_DISPLAYING,
  NAV_TO_CONTENT,
  IS_MENU_OPEN,
  SET_REF,
}

export const FETCH_MENU = "FETCH_MENU";

export const FETCH_POSTS = "FETCH_POSTS";
export const FETCH_POST = "FETCH_POST";

export const FETCH_CATEGORY = "FETCH_CATEGORY";
export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const FETCH_CATEGORY_POSTS = "FETCH_CATEGORY_POSTS";

export const FETCH_PAGE = "FETCH_PAGE";

export const FETCH_SINGULAR = "FETCH_SINGULAR";

export const IS_FETCHING = "IS_FETCHING";
export const IS_DISPLAYING = "IS_DISPLAYING";

export const NAV_TO_CONTENT = "NAV_TO_CONTENT";

export const IS_MENU_OPEN = "IS_MENU_OPEN";

export const SET_REF = "SET_REF";
